foreground = "#d4be98"
background = "#292828"
caret = "#d4be98"
line_highlight = "#38343290"
misspelling = "#b85651"
accent = "#a9b665"
find_highlight = "#8f9a5240"
find_highlight_foreground = "#a9b665"
selection = "#504945b0"
gutter = "#292828"
shadow = "#32302f7f"
guide = "#a8998420"
gutter_foreground = "#504945b0"
line_diff_added = "#72966c30"
line_diff_modified = "#7daea3a0"
line_diff_deleted = "#b8565130"
brackets_options = "underline"
inactive_selection = "#45403d48"
inactive_selection_foreground = "#a89984"
stack_guide = "#928374"
highlight = "#8f9a5240"
tags_options = "stippled_underline"
brackets_foreground = "#504945b0"
bracket_contents_options = "underline"
tags_foreground = "#504945d0"
active_guide = "#d4be98"
fold_marker = "#a9b665"
block_caret = "#d4be98"
